version: '3.7'

services:
  backend:
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND_FLASKAPP}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL_FLASKAPP}"
      - "traefik.port=5000"
      - "traefik.enable=true"
    networks:
      - default
      - prod

  phpmyadmin:
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND_PHPMYADMIN}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL_PHPMYADMIN}"
      - "traefik.enable=true"
    networks:
      - default
      - prod

  keycloak:
    environment:
      - PROXY_ADDRESS_FORWARDING=true
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND_KEYCLOAK}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL_KEYCLOAK}"
      - "traefik.enable=true"
    networks:
      - default
      - prod

  keycloak-db-admin:
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND_KEYCLOAK_DB_ADMIN}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL_KEYCLOAK_DB_ADMIN}"
      - "traefik.enable=true"
    networks:
      - default
      - prod

networks:
  prod:
    external: true
    name: ${TRAEFIK_NETWORK}
