version: "3.7"

services:
  backend:
    volumes:
      - ./webapp:/usr/src/app
      - ./venv/src/melampus:/usr/local/lib/python3.6/site-packages/melampus
      - /data/imagine-data:/imagine-data
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - DEBUGGER_IP=${DEBUGGER_IP}
      - DEBUGGER_PORT=${DEBUGGER_PORT}
      - GEVENT_SUPPORT=True
      - AUTHLIB_INSECURE_TRANSPORT=1
      - KHEOPS_ALBUM_TOKEN=${KHEOPS_ALBUM_TOKEN}
    extra_hosts:
      - "roger:153.109.130.143"

  celery:
    extra_hosts:
      - "roger:153.109.130.143"
    volumes:
      - ./workers:/usr/src/app
      - /data/imagine-data:/imagine-data
    environment:
      #- CELERY_RDB_HOST=0.0.0.0
      #- CELERY_RDB_PORT=34000
      - DEBUGGER_IP=${DEBUGGER_IP}
      - DEBUGGER_PORT_CELERY=${DEBUGGER_PORT_CELERY}
      - PYTHON_ENV=nodebug
    #ports:
      #- 34000-34100:34000-34100
    command: ["celery", "worker", "--app=tasks", "--loglevel=INFO", "--pool=solo"]
    #command: ["celery", "worker", "--app=tasks", "--loglevel=INFO"]

  flower:
    ports:
      - 5555:5555

  phpmyadmin:
    ports:
      - 8888:80

  keycloak:
    ports:
      - 8081:8080

  keycloak-db:
    ports:
      - 6543:5432

  keycloak-db-admin:
    ports:
      - 8889:80

  ohif:
    ports:
      - 4567:80

  redis:
    ports:
      - 6379:6379

  redis-socket:
    ports:
      - 6380:6379
