version: '3.7'

services:
  backend:
    restart: unless-stopped

  celery:
    restart: unless-stopped

  flower:
    restart: unless-stopped

  db:
    restart: unless-stopped

  phpmyadmin:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  redis-socket:
    restart: unless-stopped

  keycloak:
    restart: unless-stopped

  keycloak-db:
    restart: unless-stopped

  keycloak-db-admin:
    restart: unless-stopped

  ohif:
    restart: unless-stopped