version: '3.9'

services:
  backend:
    restart: unless-stopped

  celery_extraction:
    restart: unless-stopped

  celery_training:
    restart: unless-stopped

  flower:
    restart: unless-stopped

  db:
    restart: unless-stopped

  phpmyadmin:
    restart: unless-stopped

  keycloak:
    restart: unless-stopped

  keycloak-db:
    restart: unless-stopped

  ohif:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  redis-socket:
    restart: unless-stopped
