version: "3.7"

# Host mappings
x-host-mappings: &host-mappings
  extra_hosts:
    - host.docker.internal:host-gateway
    - keycloak:host-gateway

services:
  backend:
    environment:
      - DB_AUTOMIGRATE=1
    restart: unless-stopped
    ports:
      - 5000:5000
    <<: *host-mappings

  celery_extraction:
    restart: unless-stopped
    <<: *host-mappings

  celery_training:
    restart: unless-stopped
    <<: *host-mappings

  flower:
    restart: unless-stopped
    ports:
      - 3333:3333

  db:
    restart: unless-stopped

  phpmyadmin:
    restart: unless-stopped
    ports:
      - 8888:80

  keycloak:
    restart: unless-stopped
    ports:
      - 8081:8080

  keycloak-db:
    restart: unless-stopped

  ohif:
    restart: unless-stopped
    ports:
      - 4567:80

  redis:
    ports:
      - 6379:6379

  redis-socket:
    ports:
      - 6380:6379
