version: '3.7'

services:
  backend:
    env_file:
      - .env
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND_FLASKAPP}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL_FLASKAPP}"
      - "traefik.port=5000"
      - "traefik.enable=true"
    networks:
      - default
      - prod

  celery_extraction:
    env_file:
      - .env

  celery_training:
    env_file:
      - .env

  phpmyadmin:
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND_PHPMYADMIN}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL_PHPMYADMIN}"
      - "traefik.enable=true"
    networks:
      - default
      - prod

  keycloak:
    environment:
      - PROXY_ADDRESS_FORWARDING=true
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND_KEYCLOAK}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL_KEYCLOAK}"
      - "traefik.enable=true"
    networks:
      - default
      - prod

  ohif:
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND_OHIF}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL_OHIF}"
      - "traefik.enable=true"
    networks:
      - default
      - prod

  flower:
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND_FLOWER}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL_FLOWER}"
      - "traefik.enable=true"
      - "traefik.frontend.whitelistSourceRange=192.168.1.35/32"
    networks:
      - default
      - prod

networks:
  prod:
    external: true
    name: ${TRAEFIK_NETWORK}
