version: '3.7'

services:
  backend:
    build: webapp
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - CELERY_BROKER_URL=${CELERY_REDIS_URL}
      - CELERY_RESULT_BACKEND=${CELERY_REDIS_URL}
      - SOCKET_MESSAGE_QUEUE=${SOCKET_REDIS_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - KEYCLOAK_IMAGINE_CLIENT_ID=${KEYCLOAK_IMAGINE_CLIENT_ID}
      - KEYCLOAK_IMAGINE_CLIENT_SECRET=${KEYCLOAK_IMAGINE_CLIENT_SECRET}
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_REALM_PUBLIC_KEY=${KEYCLOAK_REALM_PUBLIC_KEY}
      - KEYCLOAK_KHEOPS_AUTH_CLIENT_ID=${KEYCLOAK_KHEOPS_AUTH_CLIENT_ID}
      - KEYCLOAK_KHEOPS_AUTH_CLIENT_SECRET=${KEYCLOAK_KHEOPS_AUTH_CLIENT_SECRET}
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KHEOPS_BASE_URL=${KHEOPS_BASE_URL}
      - KHEOPS_TOKEN=${KHEOPS_TOKEN}
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - backend-data:/tmp

  celery:
    build: workers
    environment:
      - KHEOPS_BASE_URL=${KHEOPS_BASE_URL}
      - KHEOPS_TOKEN=${KHEOPS_TOKEN}
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_KHEOPS_AUTH_CLIENT_ID=${KEYCLOAK_KHEOPS_AUTH_CLIENT_ID}
      - KEYCLOAK_KHEOPS_AUTH_CLIENT_SECRET=${KEYCLOAK_KHEOPS_AUTH_CLIENT_SECRET}
      - CELERY_BROKER_URL=${CELERY_REDIS_URL}
      - CELERY_RESULT_BACKEND=${CELERY_REDIS_URL}
      - SOCKET_MESSAGE_QUEUE=${SOCKET_REDIS_URL}
    volumes:
      - backend-data:/tmp

  flower:
    build: ./flower
    command: ["flower", "--broker=${CELERY_REDIS_URL}", "--result-backend=${CELERY_REDIS_URL}"]
    ports:
        - 5555:5555

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  phpmyadmin:
    image:                 phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY:       1
      PMA_HOST:            db
      PMA_PORT:            3306
    volumes:
      - /sessions
    ports:
      - 8888:80
    depends_on:
      - db

  redis:
    image: redis

  redis-socket:
    image: redis

  keycloak:
    image: jboss/keycloak
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - DB_VENDOR=mysql
      - DB_ADDR=keycloak-db
      - DB_DATABASE=${KEYCLOAK_DB}
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - ./keycloak_theme:/opt/jboss/keycloak/themes/imagine
    depends_on:
      - keycloak-db

  keycloak-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${KEYCLOAK_DB_ROOT_PASSWORD}
      - MYSQL_USER=${KEYCLOAK_DB_USER}
      - MYSQL_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - MYSQL_DATABASE=${KEYCLOAK_DB}

  keycloak-phpmyadmin:
    image:                 phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY:       1
      PMA_HOST:            keycloak-db
      PMA_PORT:            3306
    volumes:
      - /sessions
    ports:
      - 8889:80
    depends_on:
      - keycloak-db



volumes:
  backend-data:
