version: '3.7'

services:
  backend:
    environment:
      - DB_AUTOMIGRATE=1
    restart: unless-stopped
    ports:
      - 5000:5000
    extra_hosts:
      - host.docker.internal:host-gateway
      - keycloak:host-gateway

  celery_extraction:
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
      - keycloak:host-gateway

  celery_training:
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
      - keycloak:host-gateway

  flower:
    restart: unless-stopped
    ports:
      - 3333:3333

  db:
    restart: unless-stopped

  phpmyadmin:
    restart: unless-stopped
    ports:
      - 8888:80

  redis:
    restart: unless-stopped

  redis-socket:
    restart: unless-stopped

  keycloak:
    restart: unless-stopped
    ports:
      - 8081:8080

  keycloak-db:
    restart: unless-stopped

  keycloak-db-admin:
    restart: unless-stopped

  ohif:
    restart: unless-stopped
    ports:
      - 4567:80