version: '3.7'

services:
  backend:
    build: webapp
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - CELERY_BROKER_URL=${CELERY_REDIS_URL}
      - CELERY_RESULT_BACKEND=${CELERY_REDIS_URL}
      - SOCKET_MESSAGE_QUEUE=${SOCKET_REDIS_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - KEYCLOAK_IMAGINE_FRONTEND_CLIENT_ID=${KEYCLOAK_IMAGINE_FRONTEND_CLIENT_ID}
      - KEYCLOAK_FRONTEND_ADMIN_ROLE=${KEYCLOAK_FRONTEND_ADMIN_ROLE}
      - KEYCLOAK_IMAGINE_CLIENT_ID=${KEYCLOAK_IMAGINE_CLIENT_ID}
      - KEYCLOAK_IMAGINE_CLIENT_SECRET=${KEYCLOAK_IMAGINE_CLIENT_SECRET}
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_REALM_PUBLIC_KEY=${KEYCLOAK_REALM_PUBLIC_KEY}
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KHEOPS_BASE_URL=${KHEOPS_BASE_URL}
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - backend-data:/imagine-data
      - ./shared/imaginebackend_common/:/usr/local/lib/python3.6/imaginebackend_common
      - ./venv/lib/python3.6/site-packages/melampus:/usr/local/lib/python3.6/site-packages/melampus

  celery:
    build:
      context: .
      dockerfile: ./workers/Dockerfile
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - CELERY_BROKER_URL=${CELERY_REDIS_URL}
      - CELERY_RESULT_BACKEND=${CELERY_REDIS_URL}
      - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY}
      - CELERY_CONFIG_MODULE=celeryconfig
      - SOCKET_MESSAGE_QUEUE=${SOCKET_REDIS_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - KHEOPS_BASE_URL=${KHEOPS_BASE_URL}
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_IMAGINE_CLIENT_ID=${KEYCLOAK_IMAGINE_CLIENT_ID}
      - KEYCLOAK_IMAGINE_CLIENT_SECRET=${KEYCLOAK_IMAGINE_CLIENT_SECRET}
      - PYTHONUNBUFFERED=TRUE
      - PYTHON_ENV=production
    volumes:
      - backend-data:/imagine-data
      - ./shared/imaginebackend_common/:/usr/local/lib/python3.6/imaginebackend_common

  flower:
    build: ./flower
    command: ["flower", "--broker=${CELERY_REDIS_URL}", "--result-backend=${CELERY_REDIS_URL}"]

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  phpmyadmin:
    image:                 phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY:       1
      PMA_HOST:            db
      PMA_PORT:            3306
    volumes:
      - /sessions
    depends_on:
      - db

  redis:
    image: redis

  redis-socket:
    image: redis

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_LOGLEVEL=DEBUG
      - ROOT_LOGLEVEL=DEBUG
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-db
      - DB_DATABASE=${KEYCLOAK_DB}
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - DB_SCHEMA=public
    volumes:
      - ./keycloak_theme:/opt/jboss/keycloak/themes/imagine
      - ./createRealmsLocal.sh:/createRealmsLocal.sh
    depends_on:
      - keycloak-db
    command: ["-b", "0.0.0.0","-Dkeycloak.profile=preview"]

  keycloak-db:
    image: postgres
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_DB=${KEYCLOAK_DB}
    volumes:
      - pgdata:/var/lib/postgresql

  keycloak-db-admin:
    image:                 dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - keycloak-db

  ohif:
    image: rogerschaer/ohif:latest
    volumes:
      - ./ohif-config.js:/usr/share/nginx/html/app-config.js

volumes:
  backend-data:
  pgdata:
